### ISSUE TITLE
Cryptic "error", failing drafter.nomem.js:1

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/drafter-npm#4]
Sometimes I install Drafter NPM and when I try to use it, I get following "error":

```
/Users/honzajavorek/Workspace/dredd/node_modules/drafter.js/lib/drafter.nomem.js:1
(function (exports, require, module, __filename, __dirname) { ((function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.drafter=f()}}))((function(){var module;var Module={"ready":false,"log":(function(text){console.log("drafter.js: "+text)}),"logErr":(function(text){console.error("drafter.js: "+text)}),"onRuntimeInitialized":(function(){this.ready=true})};var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=fa
```

<img width="1199" alt="screen shot 2016-08-15 at 13 31 34" src="https://cloud.githubusercontent.com/assets/283441/17663412/a687658a-62ec-11e6-81c6-e92cbaac03e9.png">

Maybe I'm doing something wrong, but in any case, this gives me no information how to fix it. Happened to me multiple times already when installing Dredd and then running tests. Removing node_modules and reinstalling sometimes helped. Sometimes it did not.

If I gather more info, I'll let you know.

**Comment by honzajavorek** [comment]
So when Dredd has some sort of error and can't run properly, I get this message in tests. So it's probably fault of the library depending on Drafter NPM, but still, the output is very strange and should be turned into something with a nice error message.

**Comment by w-vi** [comment]
Is it possible to reproduce it or it appears randomly?

**Comment by honzajavorek** [comment]
I can try to create a reproducible situation and post it somewhere.

**Comment by honzajavorek** [comment]
Just to elaborate - I found out that it
1. doesn't happen randomly
2. does happen when something is wrong with the underlying application, not in standard situations
3. is hard to explain the situation, so it will be better to provide reproducible code

Due to 1. and 2. it's not a serious issue. It's rather developer/debugging experience. Since I learned what the error means, I am able to cope with it, but if user reports me this error back in bug report, I can say nothing about his problem. Fortunately, that didn't happen yet.

**Comment by w-vi** [comment]
Great, getting a reproducible set up is in this case important as it needs to be debugged using debug build of drafter.js, we are in the C/C++ waters here :)

**Comment by honzajavorek** [comment]
So this is how to reproduce the problem:
- Create a new folder called `drafter-crash`.
- Create two files in it, `package.json` and `index.js`:

``` json
{
  "name": "drafter-crash",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "drafter": "^1.1.0"
  }
}
```

``` js
var drafter = require('drafter');

console.log('Hello' + world);
```
- Run `npm install`. Make sure Protagonist installs.
- Run `node index.js`. You should get an error like this:

```
$ node index.js
/Users/honzajavorek/Workspace/drafter-crash/index.js:3
console.log('Hello' + world);
                      ^

ReferenceError: world is not defined
    at Object.<anonymous> (/Users/honzajavorek/Workspace/drafter-crash/index.js:3:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
```
- Remove the `node_modules/protagonist` folder so the app is forced to use `drafter.js`.
- Run `node index.js` again. You'll get completely different error, which won't help you with debugging at all:

```
$ node index.js
/Users/honzajavorek/Workspace/drafter-crash/node_modules/drafter.js/lib/drafter.nomem.js:1
(function (exports, require, module, __filename, __dirname) { ((function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.drafter=f()}}))((function(){var module;var Module={"ready":false,"log":(function(text){console.log("drafter.js: "+text)}),"logErr":(function(text){console.error("drafter.js: "+text)}),"onRuntimeInitialized":(function(){this.ready=true})};var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=fa~/Workspace/drafter-crash E=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIR
```

**Comment by openhoat** [comment]
+1 drafter handles all thrown errors, so that the original stack trace is no more usable

**Comment by w-vi** [comment]
So it looks like on OSX the output is truncated as I can see following result.

``` sh
node index.js
/home/wvi/src/drafter-crash/index.js:3
console.log('Hello' + world);
                      ^

ReferenceError: world is not defined
    at Object.<anonymous> (/home/wvi/src/drafter-crash/index.js:3:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
wvi@wvi λ ~/src/drafter-crash  node:6.0.0
❯❯❯rmf node_modules/protagonist                                                                                                                                      ⏎
wvi@wvi λ ~/src/drafter-crash  node:6.0.0
❯❯❯node index.js
/home/wvi/src/drafter-crash/node_modules/drafter.js/lib/drafter.nomem.js:1
(function (exports, require, module, __filename, __dirname) { ((function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.drafter=f()}}))((function(){var module;var Module={"ready":false,"log":(function(text){console.log("drafter.js: "+text)}),"logErr":(function(text){console.error("drafter.js: "+text)}),"onRuntimeInitialized":(function(){this.ready=true})};var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Mod

ReferenceError: world is not defined
    at Object.<anonymous> (/home/wvi/src/drafter-crash/index.js:3:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
```

**Comment by w-vi** [comment]
It looks like it boils down to the node issue https://github.com/nodejs/node/issues/6456. Will investigate if this can be fixed using the proposed workaround mentioned in the issue.

**Comment by kylef** [comment]
Looks like @honzajavorek has already deployed the workaround in Dredd; https://github.com/apiaryio/dredd/commit/2ac973f7024ed96e8859d4baf09b308a44b9164d

**Comment by w-vi** [comment]
Yes it is in dredd already but I would try to fix it for everybody else.

**Comment by kylef** [comment]
This has been resolved (https://github.com/kripken/emscripten/issues/4643 / https://github.com/apiaryio/emscripten-docker/pull/6).
